### ISSUE TITLE
Can't add identical potion to shopping list

### ISSUE THREAD

**Issue by michaelgman13** [Jerry-Licious/spire-shopping-list#2]
In my shop, I was offered 2 cultists potions of different prices (attached pic). I wanted to add both of the potions to the shopping list, but I couldn't. It would only allow one in the list. I could remove the one in the list and add the other priced one, but I couldn't get both to be in the list at the same time. 
![shoppingListModbug](https://github.com/Jerry-licious/spire-shopping-list/assets/11866301/5409d626-7032-4aa1-8e25-d84c02d8d635)

**Comment by Jerry-licious** [comment]
Identical potions being sold together is a little annoying to deal with. I'm pushing a quick patch that fixes this, but if you're unlucky enough to get two of the same with the same price then it still wouldn't work.

**Comment by michaelgman13** [comment]
Ah I see that's cool. Thanks for the quick turn around!
